/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RfisRouteImport } from './routes/rfis'
import { Route as SequencesRouteImport } from './routes/sequences'
import { Route as SubmittalsRouteImport } from './routes/submittals'
import { Route as DrawingsIndexRouteImport } from './routes/drawings.index'
import { Route as DrawingsDrawingIdRouteImport } from './routes/drawings.$drawingId'
import { Route as DrawingsSetsSetIdRouteImport } from './routes/drawings.sets.$setId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RfisRoute = RfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesRoute = SequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittalsRoute = SubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsIndexRoute = DrawingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrawingsRoute,
} as any)
const DrawingsDrawingIdRoute = DrawingsDrawingIdRouteImport.update({
  id: '/$drawingId',
  path: '/$drawingId',
  getParentRoute: () => DrawingsRoute,
} as any)
const DrawingsSetsSetIdRoute = DrawingsSetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => DrawingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drawings': typeof DrawingsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/sequences': typeof SequencesRoute
  '/submittals': typeof SubmittalsRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/drawings/sets/$setId': typeof DrawingsSetsSetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/sequences': typeof SequencesRoute
  '/submittals': typeof SubmittalsRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/drawings': typeof DrawingsIndexRoute
  '/drawings/sets/$setId': typeof DrawingsSetsSetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drawings': typeof DrawingsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/sequences': typeof SequencesRoute
  '/submittals': typeof SubmittalsRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/drawings/sets/$setId': typeof DrawingsSetsSetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drawings'
    | '/projects'
    | '/rfis'
    | '/sequences'
    | '/submittals'
    | '/drawings/$drawingId'
    | '/drawings/'
    | '/drawings/sets/$setId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/rfis'
    | '/sequences'
    | '/submittals'
    | '/drawings/$drawingId'
    | '/drawings'
    | '/drawings/sets/$setId'
  id:
    | '__root__'
    | '/'
    | '/drawings'
    | '/projects'
    | '/rfis'
    | '/sequences'
    | '/submittals'
    | '/drawings/$drawingId'
    | '/drawings/'
    | '/drawings/sets/$setId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawingsRoute: typeof DrawingsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RfisRoute: typeof RfisRoute
  SequencesRoute: typeof SequencesRoute
  SubmittalsRoute: typeof SubmittalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfis': {
      id: '/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof RfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences': {
      id: '/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submittals': {
      id: '/submittals'
      path: '/submittals'
      fullPath: '/submittals'
      preLoaderRoute: typeof SubmittalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/': {
      id: '/drawings/'
      path: '/'
      fullPath: '/drawings/'
      preLoaderRoute: typeof DrawingsIndexRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/drawings/$drawingId': {
      id: '/drawings/$drawingId'
      path: '/$drawingId'
      fullPath: '/drawings/$drawingId'
      preLoaderRoute: typeof DrawingsDrawingIdRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/drawings/sets/$setId': {
      id: '/drawings/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/drawings/sets/$setId'
      preLoaderRoute: typeof DrawingsSetsSetIdRouteImport
      parentRoute: typeof DrawingsRoute
    }
  }
}

interface DrawingsRouteChildren {
  DrawingsDrawingIdRoute: typeof DrawingsDrawingIdRoute
  DrawingsIndexRoute: typeof DrawingsIndexRoute
  DrawingsSetsSetIdRoute: typeof DrawingsSetsSetIdRoute
}

const DrawingsRouteChildren: DrawingsRouteChildren = {
  DrawingsDrawingIdRoute: DrawingsDrawingIdRoute,
  DrawingsIndexRoute: DrawingsIndexRoute,
  DrawingsSetsSetIdRoute: DrawingsSetsSetIdRoute,
}

const DrawingsRouteWithChildren = DrawingsRoute._addFileChildren(
  DrawingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawingsRoute: DrawingsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RfisRoute: RfisRoute,
  SequencesRoute: SequencesRoute,
  SubmittalsRoute: SubmittalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
