/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangeOrdersRouteImport } from './routes/change-orders'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as FieldRouteImport } from './routes/field'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HoldsRouteImport } from './routes/holds'
import { Route as IdsRouteImport } from './routes/ids'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookaheadRouteImport } from './routes/lookahead'
import { Route as PiecesRouteImport } from './routes/pieces'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RfisRouteImport } from './routes/rfis'
import { Route as RoadblocksRouteImport } from './routes/roadblocks'
import { Route as SequencesRouteImport } from './routes/sequences'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SubmittalsRouteImport } from './routes/submittals'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TransmittalsRouteImport } from './routes/transmittals'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as WorkPackagesRouteImport } from './routes/work-packages'
import { Route as DrawingsIndexRouteImport } from './routes/drawings.index'
import { Route as DrawingsDrawingIdRouteImport } from './routes/drawings.$drawingId'
import { Route as PrintFieldRouteImport } from './routes/print.field'
import { Route as PrintShopRouteImport } from './routes/print.shop'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DrawingsSetsSetIdRouteImport } from './routes/drawings.sets.$setId'
import { Route as PrintTransmittalTrIdRouteImport } from './routes/print.transmittal.$trId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeOrdersRoute = ChangeOrdersRouteImport.update({
  id: '/change-orders',
  path: '/change-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldsRoute = HoldsRouteImport.update({
  id: '/holds',
  path: '/holds',
  getParentRoute: () => rootRouteImport,
} as any)
const IdsRoute = IdsRouteImport.update({
  id: '/ids',
  path: '/ids',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookaheadRoute = LookaheadRouteImport.update({
  id: '/lookahead',
  path: '/lookahead',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesRoute = PiecesRouteImport.update({
  id: '/pieces',
  path: '/pieces',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RfisRoute = RfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadblocksRoute = RoadblocksRouteImport.update({
  id: '/roadblocks',
  path: '/roadblocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesRoute = SequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittalsRoute = SubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmittalsRoute = TransmittalsRouteImport.update({
  id: '/transmittals',
  path: '/transmittals',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPackagesRoute = WorkPackagesRouteImport.update({
  id: '/work-packages',
  path: '/work-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsIndexRoute = DrawingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrawingsRoute,
} as any)
const DrawingsDrawingIdRoute = DrawingsDrawingIdRouteImport.update({
  id: '/$drawingId',
  path: '/$drawingId',
  getParentRoute: () => DrawingsRoute,
} as any)
const PrintFieldRoute = PrintFieldRouteImport.update({
  id: '/print/field',
  path: '/print/field',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintShopRoute = PrintShopRouteImport.update({
  id: '/print/shop',
  path: '/print/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsSetsSetIdRoute = DrawingsSetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => DrawingsRoute,
} as any)
const PrintTransmittalTrIdRoute = PrintTransmittalTrIdRouteImport.update({
  id: '/print/transmittal/$trId',
  path: '/print/transmittal/$trId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-orders': typeof ChangeOrdersRoute
  '/deliveries': typeof DeliveriesRoute
  '/drawings': typeof DrawingsRouteWithChildren
  '/field': typeof FieldRoute
  '/help': typeof HelpRoute
  '/holds': typeof HoldsRoute
  '/ids': typeof IdsRoute
  '/login': typeof LoginRoute
  '/lookahead': typeof LookaheadRoute
  '/pieces': typeof PiecesRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/roadblocks': typeof RoadblocksRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/submittals': typeof SubmittalsRoute
  '/tasks': typeof TasksRoute
  '/transmittals': typeof TransmittalsRoute
  '/viewer': typeof ViewerRoute
  '/work-packages': typeof WorkPackagesRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/print/field': typeof PrintFieldRoute
  '/print/shop': typeof PrintShopRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/drawings/sets/$setId': typeof DrawingsSetsSetIdRoute
  '/print/transmittal/$trId': typeof PrintTransmittalTrIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-orders': typeof ChangeOrdersRoute
  '/deliveries': typeof DeliveriesRoute
  '/field': typeof FieldRoute
  '/help': typeof HelpRoute
  '/holds': typeof HoldsRoute
  '/ids': typeof IdsRoute
  '/login': typeof LoginRoute
  '/lookahead': typeof LookaheadRoute
  '/pieces': typeof PiecesRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/roadblocks': typeof RoadblocksRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/submittals': typeof SubmittalsRoute
  '/tasks': typeof TasksRoute
  '/transmittals': typeof TransmittalsRoute
  '/viewer': typeof ViewerRoute
  '/work-packages': typeof WorkPackagesRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/print/field': typeof PrintFieldRoute
  '/print/shop': typeof PrintShopRoute
  '/drawings': typeof DrawingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/drawings/sets/$setId': typeof DrawingsSetsSetIdRoute
  '/print/transmittal/$trId': typeof PrintTransmittalTrIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-orders': typeof ChangeOrdersRoute
  '/deliveries': typeof DeliveriesRoute
  '/drawings': typeof DrawingsRouteWithChildren
  '/field': typeof FieldRoute
  '/help': typeof HelpRoute
  '/holds': typeof HoldsRoute
  '/ids': typeof IdsRoute
  '/login': typeof LoginRoute
  '/lookahead': typeof LookaheadRoute
  '/pieces': typeof PiecesRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/roadblocks': typeof RoadblocksRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/submittals': typeof SubmittalsRoute
  '/tasks': typeof TasksRoute
  '/transmittals': typeof TransmittalsRoute
  '/viewer': typeof ViewerRoute
  '/work-packages': typeof WorkPackagesRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/print/field': typeof PrintFieldRoute
  '/print/shop': typeof PrintShopRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/drawings/sets/$setId': typeof DrawingsSetsSetIdRoute
  '/print/transmittal/$trId': typeof PrintTransmittalTrIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-orders'
    | '/deliveries'
    | '/drawings'
    | '/field'
    | '/help'
    | '/holds'
    | '/ids'
    | '/login'
    | '/lookahead'
    | '/pieces'
    | '/portfolio'
    | '/projects'
    | '/rfis'
    | '/roadblocks'
    | '/sequences'
    | '/settings'
    | '/shop'
    | '/submittals'
    | '/tasks'
    | '/transmittals'
    | '/viewer'
    | '/work-packages'
    | '/drawings/$drawingId'
    | '/print/field'
    | '/print/shop'
    | '/drawings/'
    | '/api/auth/$'
    | '/drawings/sets/$setId'
    | '/print/transmittal/$trId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-orders'
    | '/deliveries'
    | '/field'
    | '/help'
    | '/holds'
    | '/ids'
    | '/login'
    | '/lookahead'
    | '/pieces'
    | '/portfolio'
    | '/projects'
    | '/rfis'
    | '/roadblocks'
    | '/sequences'
    | '/settings'
    | '/shop'
    | '/submittals'
    | '/tasks'
    | '/transmittals'
    | '/viewer'
    | '/work-packages'
    | '/drawings/$drawingId'
    | '/print/field'
    | '/print/shop'
    | '/drawings'
    | '/api/auth/$'
    | '/drawings/sets/$setId'
    | '/print/transmittal/$trId'
  id:
    | '__root__'
    | '/'
    | '/change-orders'
    | '/deliveries'
    | '/drawings'
    | '/field'
    | '/help'
    | '/holds'
    | '/ids'
    | '/login'
    | '/lookahead'
    | '/pieces'
    | '/portfolio'
    | '/projects'
    | '/rfis'
    | '/roadblocks'
    | '/sequences'
    | '/settings'
    | '/shop'
    | '/submittals'
    | '/tasks'
    | '/transmittals'
    | '/viewer'
    | '/work-packages'
    | '/drawings/$drawingId'
    | '/print/field'
    | '/print/shop'
    | '/drawings/'
    | '/api/auth/$'
    | '/drawings/sets/$setId'
    | '/print/transmittal/$trId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeOrdersRoute: typeof ChangeOrdersRoute
  DeliveriesRoute: typeof DeliveriesRoute
  DrawingsRoute: typeof DrawingsRouteWithChildren
  FieldRoute: typeof FieldRoute
  HelpRoute: typeof HelpRoute
  HoldsRoute: typeof HoldsRoute
  IdsRoute: typeof IdsRoute
  LoginRoute: typeof LoginRoute
  LookaheadRoute: typeof LookaheadRoute
  PiecesRoute: typeof PiecesRoute
  PortfolioRoute: typeof PortfolioRoute
  ProjectsRoute: typeof ProjectsRoute
  RfisRoute: typeof RfisRoute
  RoadblocksRoute: typeof RoadblocksRoute
  SequencesRoute: typeof SequencesRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  SubmittalsRoute: typeof SubmittalsRoute
  TasksRoute: typeof TasksRoute
  TransmittalsRoute: typeof TransmittalsRoute
  ViewerRoute: typeof ViewerRoute
  WorkPackagesRoute: typeof WorkPackagesRoute
  PrintFieldRoute: typeof PrintFieldRoute
  PrintShopRoute: typeof PrintShopRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PrintTransmittalTrIdRoute: typeof PrintTransmittalTrIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-orders': {
      id: '/change-orders'
      path: '/change-orders'
      fullPath: '/change-orders'
      preLoaderRoute: typeof ChangeOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holds': {
      id: '/holds'
      path: '/holds'
      fullPath: '/holds'
      preLoaderRoute: typeof HoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ids': {
      id: '/ids'
      path: '/ids'
      fullPath: '/ids'
      preLoaderRoute: typeof IdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookahead': {
      id: '/lookahead'
      path: '/lookahead'
      fullPath: '/lookahead'
      preLoaderRoute: typeof LookaheadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces': {
      id: '/pieces'
      path: '/pieces'
      fullPath: '/pieces'
      preLoaderRoute: typeof PiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfis': {
      id: '/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof RfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadblocks': {
      id: '/roadblocks'
      path: '/roadblocks'
      fullPath: '/roadblocks'
      preLoaderRoute: typeof RoadblocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences': {
      id: '/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submittals': {
      id: '/submittals'
      path: '/submittals'
      fullPath: '/submittals'
      preLoaderRoute: typeof SubmittalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmittals': {
      id: '/transmittals'
      path: '/transmittals'
      fullPath: '/transmittals'
      preLoaderRoute: typeof TransmittalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-packages': {
      id: '/work-packages'
      path: '/work-packages'
      fullPath: '/work-packages'
      preLoaderRoute: typeof WorkPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/': {
      id: '/drawings/'
      path: '/'
      fullPath: '/drawings/'
      preLoaderRoute: typeof DrawingsIndexRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/drawings/$drawingId': {
      id: '/drawings/$drawingId'
      path: '/$drawingId'
      fullPath: '/drawings/$drawingId'
      preLoaderRoute: typeof DrawingsDrawingIdRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/print/field': {
      id: '/print/field'
      path: '/print/field'
      fullPath: '/print/field'
      preLoaderRoute: typeof PrintFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/shop': {
      id: '/print/shop'
      path: '/print/shop'
      fullPath: '/print/shop'
      preLoaderRoute: typeof PrintShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/sets/$setId': {
      id: '/drawings/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/drawings/sets/$setId'
      preLoaderRoute: typeof DrawingsSetsSetIdRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/print/transmittal/$trId': {
      id: '/print/transmittal/$trId'
      path: '/print/transmittal/$trId'
      fullPath: '/print/transmittal/$trId'
      preLoaderRoute: typeof PrintTransmittalTrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DrawingsRouteChildren {
  DrawingsDrawingIdRoute: typeof DrawingsDrawingIdRoute
  DrawingsIndexRoute: typeof DrawingsIndexRoute
  DrawingsSetsSetIdRoute: typeof DrawingsSetsSetIdRoute
}

const DrawingsRouteChildren: DrawingsRouteChildren = {
  DrawingsDrawingIdRoute: DrawingsDrawingIdRoute,
  DrawingsIndexRoute: DrawingsIndexRoute,
  DrawingsSetsSetIdRoute: DrawingsSetsSetIdRoute,
}

const DrawingsRouteWithChildren = DrawingsRoute._addFileChildren(
  DrawingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeOrdersRoute: ChangeOrdersRoute,
  DeliveriesRoute: DeliveriesRoute,
  DrawingsRoute: DrawingsRouteWithChildren,
  FieldRoute: FieldRoute,
  HelpRoute: HelpRoute,
  HoldsRoute: HoldsRoute,
  IdsRoute: IdsRoute,
  LoginRoute: LoginRoute,
  LookaheadRoute: LookaheadRoute,
  PiecesRoute: PiecesRoute,
  PortfolioRoute: PortfolioRoute,
  ProjectsRoute: ProjectsRoute,
  RfisRoute: RfisRoute,
  RoadblocksRoute: RoadblocksRoute,
  SequencesRoute: SequencesRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  SubmittalsRoute: SubmittalsRoute,
  TasksRoute: TasksRoute,
  TransmittalsRoute: TransmittalsRoute,
  ViewerRoute: ViewerRoute,
  WorkPackagesRoute: WorkPackagesRoute,
  PrintFieldRoute: PrintFieldRoute,
  PrintShopRoute: PrintShopRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PrintTransmittalTrIdRoute: PrintTransmittalTrIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
